In [1]:

import allison
from allison.nn import Tensor,no_grad
import numpy as np
import pandas as pd

# Create a Tensor

In [2]:
# from list
tensor = Tensor([1,2,3])
tensor

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [3]:
tensor.shape

(3,)

In [4]:
len(tensor)

3

In [5]:
#from numpy
tensor = Tensor(np.random.rand(5,5))
tensor

Tensor(
[[0.31860422 0.17129537 0.24963034 0.29322863 0.81899854]
 [0.42176095 0.06196362 0.62467747 0.88202152 0.25644612]
 [0.66476224 0.55857703 0.23217641 0.56813557 0.82094157]
 [0.56437097 0.86947272 0.26940274 0.61687043 0.81752769]
 [0.09323038 0.73855918 0.60620247 0.06706473 0.20377477]], shape=(5, 5), device=cpu, requires_grad=False)

In [6]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

tensor = Tensor(data)
tensor

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

# Basic Operations

In [7]:
a = Tensor([1,2,3])
b = Tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [8]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [9]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [10]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [11]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [12]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [13]:
a = Tensor(np.random.rand(5,5))
a

Tensor(
[[0.03880022 0.5788681  0.46676032 0.59714095 0.40847425]
 [0.13888555 0.45407452 0.12164524 0.10741359 0.13458307]
 [0.18504145 0.03072697 0.56205865 0.71894168 0.08123032]
 [0.09563451 0.87001816 0.41512356 0.16745698 0.42618203]
 [0.10162781 0.21195684 0.13985485 0.10944902 0.36798337]], shape=(5, 5), device=cpu, requires_grad=False)

In [14]:
a[3,:]

Tensor(
[0.09563451 0.87001816 0.41512356 0.16745698 0.42618203], shape=(5,), device=cpu, requires_grad=False)

In [15]:
a[3,3]

Tensor(
0.16745698262582076, shape=(), device=cpu, requires_grad=False)

In [16]:
a[:,3]

Tensor(
[0.59714095 0.10741359 0.71894168 0.16745698 0.10944902], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [17]:
a = Tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [18]:
b = Tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [19]:
c = a + b
print(c)
print(c._prev)
print(f'grad(c) {c.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
{Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)}
grad(c) [0 0 0]


In [20]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [21]:
with no_grad():
    a = Tensor([1,2,3], requires_grad=True)
    b = Tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

set()

# Using GPU

In [22]:
device = 'gpu' if allison.is_cuda_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [23]:
a = Tensor(np.random.rand(5,5), device=device)
b = Tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.24797537 1.66556173 1.67107847 1.29055    0.95989843]
 [1.01726447 1.80520796 1.47365013 0.49552864 1.26836448]
 [0.62981736 1.09959042 1.29228019 0.68304916 1.65954496]
 [0.49235684 0.79209163 1.6603502  0.81596813 0.90037381]
 [1.2571134  1.3391439  1.75969752 1.43919022 1.27865189]], shape=(5, 5), device=gpu, requires_grad=False)
set()
gpu


In [24]:
a = Tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = Tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.78889659 0.6174487  1.62394412 0.59863671 0.43649237]
 [1.37616153 0.94625794 1.34525431 1.09788437 0.68287309]
 [0.44715904 1.08956758 0.77526438 0.38911335 0.9935127 ]
 [0.22459075 0.36240514 1.71828925 0.97456882 1.89462703]
 [0.77739141 0.66496929 1.2484758  1.61188459 0.68858161]], shape=(5, 5), device=gpu, requires_grad=True)
{Tensor(
[[0.54078005 0.28785271 0.79776526 0.09136004 0.09148428]
 [0.95353484 0.68332848 0.72086851 0.74824459 0.31493497]
 [0.20758296 0.29979507 0.288986   0.29105997 0.42799971]
 [0.19904288 0.13389404 0.91842881 0.49992116 0.95192458]
 [0.50570521 0.40126841 0.721743   0.9248738  0.34102821]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.24811654 0.32959599 0.82617885 0.50727667 0.34500809]
 [0.4226267  0.26292946 0.6243858  0.34963977 0.36793812]
 [0.23957607 0.78977251 0.48627838 0.09805338 0.56551299]
 [0.02554787 0.2285111  0.79986044 0.47464766 0.94270245]
 [0.2716862  0.26370089 0.5267328  0.68701079 0.34755341]], shape=