[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/Allison/blob/develop/examples/nn/1-tensor.ipynb)


In [29]:
%reload_ext autoreload
%autoreload 2

In [ ]:
import allison
import numpy as np
import pandas as pd

# Create a Tensor

In [31]:
# from list
a = allison.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [32]:
a.shape

(3,)

In [33]:
len(a)

3

In [34]:
#from numpy
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.23245875 0.92769839 0.98303094 0.56750773 0.466072  ]
 [0.54668178 0.85959801 0.88628359 0.35237337 0.26362098]
 [0.36830723 0.23266667 0.08792604 0.83949587 0.02487993]
 [0.48058726 0.94717331 0.28449211 0.77933928 0.83661446]
 [0.24397921 0.46148947 0.24579469 0.65910337 0.18114033]], shape=(5, 5), device=cpu, requires_grad=False)

In [35]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = allison.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

# Basic Operations

In [36]:
a = allison.tensor([1,2,3])
b = allison.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [37]:
c = a + b
c

Tensor(
[[4]
 [6]
 [8]], shape=(3, 1), device=cpu, requires_grad=False)

In [38]:
c = a - b
c

Tensor(
[[-2]
 [-2]
 [-2]], shape=(3, 1), device=cpu, requires_grad=False)

In [39]:
c = a * b
c

Tensor(
[[ 3]
 [ 8]
 [15]], shape=(3, 1), device=cpu, requires_grad=False)

In [40]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [41]:
c = a**2
c

Tensor(
[[1]
 [4]
 [9]], shape=(3, 1), device=cpu, requires_grad=False)

# Spliting

In [42]:
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.737562   0.70758079 0.16277061 0.64250494 0.29026015]
 [0.53771251 0.1865733  0.22927281 0.77674571 0.50737425]
 [0.5910008  0.28192313 0.31665087 0.20793    0.17141074]
 [0.26609882 0.51289905 0.9949479  0.81357255 0.05441107]
 [0.3995671  0.52925472 0.1282275  0.02470626 0.90043181]], shape=(5, 5), device=cpu, requires_grad=False)

In [43]:
a[3,:]

Tensor(
[[0.26609882]
 [0.51289905]
 [0.9949479 ]
 [0.81357255]
 [0.05441107]], shape=(5, 1), device=cpu, requires_grad=False)

In [44]:
a[3,3]

Tensor(
0.8135725531865975, shape=(), device=cpu, requires_grad=False)

In [45]:
a[:,3]

Tensor(
[[0.64250494]
 [0.77674571]
 [0.20793   ]
 [0.81357255]
 [0.02470626]], shape=(5, 1), device=cpu, requires_grad=False)

# Auto Grad

In [46]:
a = allison.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [47]:
b =allison.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [48]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[[4]
 [6]
 [8]], shape=(3, 1), device=cpu, requires_grad=True)
{Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True), Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)}
grad(a) [0 0 0]
grad(b) [0 0 0]


In [49]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [3 3 3]
grad(b) [3 3 3]


In [50]:
with allison.no_grad():
    a = allison.tensor([1,2,3], requires_grad=True)
    b = allison.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

set()

# Using GPU

In [51]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [52]:
a = allison.tensor(np.random.rand(5,5), device=device)
b = allison.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.97288629 0.61006018 0.5177919  1.05083056 0.39758187]
 [0.68626086 1.05843103 1.15684517 0.76975443 1.07846854]
 [0.92175222 0.9545834  0.58208343 0.27046347 1.20071123]
 [0.84117336 0.70823409 1.0778252  0.6607275  0.41382636]
 [1.73645269 0.84830937 0.35032234 0.25371302 1.41976753]], shape=(5, 5), device=gpu, requires_grad=False)
set()
gpu


In [53]:
a = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.71347621 0.82425367 1.41847814 0.72530192 0.93697619]
 [0.71803662 1.00051024 0.46879198 0.72405522 1.0924001 ]
 [0.66018851 0.37869752 0.62334432 0.90929668 1.52402444]
 [1.40350501 0.53861885 0.93402124 1.3383572  1.03865854]
 [0.53746916 0.60416595 1.31170128 1.50673159 0.93681634]], shape=(5, 5), device=gpu, requires_grad=True)
{Tensor(
[[0.25780782 0.55467521 0.42463074 0.37005374 0.43747353]
 [0.53894564 0.40395057 0.04555296 0.39621211 0.5914497 ]
 [0.33140489 0.02822374 0.50418857 0.35321929 0.87102832]
 [0.99776174 0.1078702  0.16181754 0.45142301 0.81223553]
 [0.29631509 0.58676892 0.87199407 0.59198526 0.14424072]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.45566839 0.26957845 0.9938474  0.35524817 0.49950266]
 [0.17909099 0.59655967 0.42323902 0.32784311 0.5009504 ]
 [0.32878362 0.35047379 0.11915574 0.5560774  0.65299612]
 [0.40574327 0.43074865 0.7722037  0.88693419 0.22642301]
 [0.24115407 0.01739704 0.43970721 0.91474633 0.79257562]], shape=