In [33]:
%reload_ext autoreload
%autoreload 2

In [34]:
import allison
import numpy as np
import pandas as pd

# Create a Tensor

In [35]:
# from list
a = allison.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [36]:
a.shape

(3,)

In [37]:
len(a)

3

In [38]:
#from numpy
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.06245631 0.3045695  0.81344931 0.78435386 0.5648265 ]
 [0.73153147 0.97899725 0.62779698 0.66489372 0.22244782]
 [0.80005584 0.31051096 0.44209009 0.8202569  0.45593719]
 [0.40234749 0.06003288 0.96427845 0.18883499 0.38330772]
 [0.41848291 0.66712756 0.37900124 0.38288139 0.73358875]], shape=(5, 5), device=cpu, requires_grad=False)

In [39]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = allison.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

# Basic Operations

In [40]:
a = allison.tensor([1,2,3])
b = allison.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [41]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [42]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [43]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [44]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [45]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [46]:
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.43880342 0.70697168 0.06629456 0.60270537 0.58799029]
 [0.04628299 0.84102674 0.42481    0.44619701 0.63655283]
 [0.4403112  0.35204719 0.8521801  0.40627013 0.04062205]
 [0.62276991 0.29882759 0.74158805 0.67343604 0.68385639]
 [0.20641517 0.76837224 0.90103041 0.20520419 0.13507   ]], shape=(5, 5), device=cpu, requires_grad=False)

In [47]:
a[3,:]

Tensor(
[0.62276991 0.29882759 0.74158805 0.67343604 0.68385639], shape=(5,), device=cpu, requires_grad=False)

In [48]:
a[3,3]

Tensor(
0.673436035117872, shape=(), device=cpu, requires_grad=False)

In [49]:
a[:,3]

Tensor(
[0.60270537 0.44619701 0.40627013 0.67343604 0.20520419], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [50]:
a = allison.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [51]:
b =allison.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [52]:
c = a + b
print(c)
print(c._prev)
print(f'grad(c) {c.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
{Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)}
grad(c) [0 0 0]


In [53]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [54]:
with allison.no_grad():
    a = allison.tensor([1,2,3], requires_grad=True)
    b = allison.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

set()

# Using GPU

In [55]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [56]:
a = allison.tensor(np.random.rand(5,5), device=device)
b = allison.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.02101129 0.81497586 0.18064427 0.3888782  1.60734569]
 [0.19113617 1.00197303 1.06228009 1.18713517 0.77531542]
 [1.31239199 0.44785215 1.57848606 1.25582296 0.97354801]
 [1.32948642 0.15688473 1.46616455 0.49573514 0.79877003]
 [0.7894649  1.51294482 0.94737254 0.82747926 0.63583688]], shape=(5, 5), device=gpu, requires_grad=False)
set()
gpu


In [57]:
a = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.86685296 1.22238503 0.81494858 0.69937672 1.13059523]
 [1.51703339 0.06995423 1.02681471 1.25912641 0.66631336]
 [0.78372667 0.18828655 1.46354201 0.50949888 1.12429371]
 [1.14918523 0.80954281 1.51907119 1.25290102 1.27435893]
 [1.75376936 1.21156456 0.94778411 1.3844413  1.00311001]], shape=(5, 5), device=gpu, requires_grad=True)
{Tensor(
[[0.46115272 0.95170979 0.52222213 0.27507557 0.72634922]
 [0.99941704 0.04885344 0.38234215 0.70374396 0.15026472]
 [0.56605287 0.18196619 0.71937268 0.4764482  0.16582586]
 [0.68521845 0.15941081 0.88454508 0.93244749 0.86800798]
 [0.9292352  0.73512658 0.47080663 0.68092054 0.80541388]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.40570024 0.27067524 0.29272645 0.42430116 0.40424601]
 [0.51761635 0.02110079 0.64447256 0.55538245 0.51604864]
 [0.2176738  0.00632036 0.74416933 0.03305069 0.95846785]
 [0.46396678 0.650132   0.63452611 0.32045353 0.40635095]
 [0.82453415 0.47643799 0.47697747 0.70352076 0.19769612]], shape=