In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import allison
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = allison.tensor([1,2,3])
a

AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
a.shape

(3,)

In [ ]:
len(a)

3

In [ ]:
#from numpy
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.39025542 0.56914096 0.18616635 0.67153407 0.43433586]
 [0.67608829 0.53197853 0.37680726 0.81839682 0.34947871]
 [0.82384394 0.6709698  0.50089118 0.33923826 0.68138901]
 [0.59522274 0.447798   0.67441466 0.4593417  0.57461077]
 [0.69957821 0.65187965 0.25121701 0.09584873 0.77833419]], shape=(5, 5), device=cpu, requires_grad=False)

In [ ]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = allison.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

# Basic Operations

In [ ]:
a = allison.tensor([1,2,3])
b = allison.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [ ]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [ ]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [ ]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [ ]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [ ]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [ ]:
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.84559688 0.20271491 0.64687423 0.48315009 0.49974395]
 [0.11771543 0.88000536 0.03918164 0.12718864 0.94091655]
 [0.78854579 0.43619784 0.5707309  0.86808068 0.66866391]
 [0.55577279 0.13955017 0.9297074  0.79283322 0.22979786]
 [0.80722598 0.9781505  0.97778922 0.08570376 0.07322975]], shape=(5, 5), device=cpu, requires_grad=False)

In [ ]:
a[3,:]

Tensor(
[0.55577279 0.13955017 0.9297074  0.79283322 0.22979786], shape=(5,), device=cpu, requires_grad=False)

In [ ]:
a[3,3]

Tensor(
0.7928332165581825, shape=(), device=cpu, requires_grad=False)

In [ ]:
a[:,3]

Tensor(
[0.48315009 0.12718864 0.86808068 0.79283322 0.08570376], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [ ]:
a = allison.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [ ]:
b =allison.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [ ]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
{Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True), Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)}
grad(a) [0 0 0]
grad(b) [0 0 0]


In [ ]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [ ]:
with allison.no_grad():
    a = allison.tensor([1,2,3], requires_grad=True)
    b = allison.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

set()

# Using GPU

In [ ]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [ ]:
a = allison.tensor(np.random.rand(5,5), device=device)
b = allison.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.505506   0.09168354 1.0971053  0.97410807 1.60565707]
 [1.35088171 1.39570559 1.24320245 0.41986138 0.95479265]
 [0.51651528 0.77108142 0.85257745 1.33497174 0.81564492]
 [1.80073228 0.94274162 0.96458054 1.21810571 0.51665486]
 [0.93470475 1.27653038 1.69220346 1.16747423 0.45014258]], shape=(5, 5), device=gpu, requires_grad=False)
set()
gpu


In [ ]:
a = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.40964729 0.95398749 0.58750206 0.98880084 1.15719503]
 [1.7721483  1.28522    1.58005137 0.20603527 0.81712912]
 [0.5192179  1.04110505 0.80356012 0.54373299 0.84753315]
 [1.3657009  0.62737733 0.874699   0.99855389 1.56754428]
 [1.81366713 0.85011372 0.99829412 0.49636736 0.98224201]], shape=(5, 5), device=gpu, requires_grad=True)
{Tensor(
[[0.4389974  0.09830151 0.41418217 0.96765038 0.21167338]
 [0.98769264 0.59713931 0.61873129 0.16281722 0.55243285]
 [0.06522504 0.88926413 0.19440218 0.53348259 0.62771275]
 [0.55016559 0.61314764 0.01471125 0.14064524 0.82535731]
 [0.95549961 0.43985206 0.29162295 0.08172781 0.58117971]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.97064989 0.85568598 0.17331988 0.02115046 0.94552165]
 [0.78445566 0.68808068 0.96132008 0.04321806 0.26469627]
 [0.45399285 0.15184092 0.60915794 0.0102504  0.2198204 ]
 [0.81553532 0.01422969 0.85998775 0.85790865 0.74218697]
 [0.85816753 0.41026166 0.70667117 0.41463956 0.40106229]], shape=