[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/Allison/blob/develop/examples/nn/1-tensor.ipynb)


In [54]:
%reload_ext autoreload
%autoreload 2

In [55]:
import allison
import numpy as np
import pandas as pd

# Create a Tensor

In [56]:
# from list
a = allison.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [57]:
a.shape

(3,)

In [58]:
len(a)

3

In [59]:
#from numpy
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.92931769 0.66331231 0.29267587 0.35480465 0.95797617]
 [0.64592045 0.6297462  0.38657981 0.05459379 0.72185996]
 [0.79540716 0.3483396  0.31532206 0.31431217 0.4321838 ]
 [0.47836747 0.67245849 0.71244938 0.16344985 0.85738276]
 [0.96042974 0.27439647 0.4109225  0.3784135  0.18356263]], shape=(5, 5), device=cpu, requires_grad=False)

In [60]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = allison.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

# Basic Operations

In [61]:
a = allison.tensor([1,2,3])
b = allison.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [62]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [63]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [64]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [65]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [66]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [67]:
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.6888692  0.2820976  0.69341251 0.0904528  0.18347662]
 [0.43061426 0.3411566  0.446861   0.05712607 0.84945014]
 [0.84943604 0.7211343  0.04487242 0.3878999  0.04291168]
 [0.09008654 0.29542021 0.769002   0.57331906 0.96670778]
 [0.85035639 0.98254437 0.50718066 0.95656938 0.12013774]], shape=(5, 5), device=cpu, requires_grad=False)

In [68]:
a[3,:]

Tensor(
[0.09008654 0.29542021 0.769002   0.57331906 0.96670778], shape=(5,), device=cpu, requires_grad=False)

In [69]:
a[3,3]

Tensor(
0.5733190563667947, shape=(), device=cpu, requires_grad=False)

In [70]:
a[:,3]

Tensor(
[0.0904528  0.05712607 0.3878999  0.57331906 0.95656938], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [71]:
a = allison.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [72]:
b =allison.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [73]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
{Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)}
grad(a) [0 0 0]
grad(b) [0 0 0]


In [74]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [75]:
with allison.no_grad():
    a = allison.tensor([1,2,3], requires_grad=True)
    b = allison.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

set()

# Using GPU

In [76]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [77]:
a = allison.tensor(np.random.rand(5,5), device=device)
b = allison.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.29885778 0.29438157 1.84152194 0.68863221 0.83885759]
 [1.22516954 1.02749715 1.27369375 0.64454149 0.33237494]
 [1.05747812 0.51386481 0.73314782 0.45439371 1.19821742]
 [1.02752206 0.81857168 1.62771841 0.53107887 1.40086803]
 [0.91680072 0.90647835 1.54338432 0.90264509 1.74147915]], shape=(5, 5), device=gpu, requires_grad=False)
set()
gpu


In [78]:
a = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.3123474  0.61931442 1.28526947 0.55716934 1.25286754]
 [0.79226651 1.01692402 1.3202954  0.89369901 1.28740803]
 [1.53238032 0.91823165 0.41085126 0.53064879 0.35720309]
 [1.44270475 1.54499966 0.99358193 1.29530992 0.53860299]
 [1.20690432 1.22902913 1.31428271 0.9945178  0.63406583]], shape=(5, 5), device=gpu, requires_grad=True)
{Tensor(
[[0.36305803 0.53184361 0.39361103 0.51549647 0.71705166]
 [0.68186558 0.64868475 0.78291464 0.14797189 0.79028559]
 [0.95233005 0.29884162 0.03654428 0.26081966 0.23711553]
 [0.56809747 0.8656066  0.89086906 0.91378493 0.32839785]
 [0.79306705 0.3392542  0.62924966 0.59219748 0.39412053]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.94928937 0.08747081 0.89165844 0.04167287 0.53581588]
 [0.11040093 0.36823927 0.53738076 0.74572712 0.49712243]
 [0.58005028 0.61939003 0.37430699 0.26982913 0.12008756]
 [0.87460728 0.67939305 0.10271287 0.38152499 0.21020514]
 [0.41383727 0.88977492 0.68503304 0.40232032 0.2399453 ]], shape=