[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/Allison/blob/develop/examples/nn/2-layers.ipynb)

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from allison import tensor
from allison.nn import Relu,Linear,BatchNorm1D
import allison

In [3]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [4]:
examples = 10
features = 2
classes = 3

In [5]:
# create random data
X = tensor(np.random.randn(examples, features))
X

Tensor(
[[-2.44217107 -0.67975745]
 [-0.22369563 -0.12025912]
 [-1.06689784  1.53248021]
 [ 0.61026138 -1.9042544 ]
 [ 0.5065648   0.41821679]
 [-0.07362594 -2.27419377]
 [ 0.1207916  -0.28540795]
 [-1.00211107 -0.79074324]
 [-1.18210791  0.87701617]
 [ 0.01163097  0.13995182]], shape=(10, 2), device=cpu, requires_grad=False)

In [6]:
relu = Relu()
l1 = Linear(2, 3)
bn = BatchNorm1D(3)

In [7]:
l1(X)

Tensor(
[[-1.97716244  1.66628324  2.12121745]
 [-0.2817318   0.16638221  0.2782659 ]
 [ 2.31057144  0.2940245  -1.72207656]
 [-3.10480124  0.07556942  2.47295194]
 [ 0.89112209 -0.41137911 -0.8413631 ]
 [-3.97007501  0.58477776  3.32697454]
 [-0.45576595 -0.00674678  0.35699012]
 [-1.69936639  0.80513069  1.61144332]
 [ 1.13562341  0.52049185 -0.71942206]
 [ 0.24663393 -0.04036232 -0.20804466]], shape=(10, 3), device=cpu, requires_grad=True)

In [8]:
relu(X)

Tensor(
[[0.         0.        ]
 [0.         0.        ]
 [0.         1.53248021]
 [0.61026138 0.        ]
 [0.5065648  0.41821679]
 [0.         0.        ]
 [0.1207916  0.        ]
 [0.         0.        ]
 [0.         0.87701617]
 [0.01163097 0.13995182]], shape=(10, 2), device=cpu, requires_grad=False)

In [9]:
relu(l1(X))

Tensor(
[[0.         1.66628324 2.12121745]
 [0.         0.16638221 0.2782659 ]
 [2.31057144 0.2940245  0.        ]
 [0.         0.07556942 2.47295194]
 [0.89112209 0.         0.        ]
 [0.         0.58477776 3.32697454]
 [0.         0.         0.35699012]
 [0.         0.80513069 1.61144332]
 [1.13562341 0.52049185 0.        ]
 [0.24663393 0.         0.        ]], shape=(10, 3), device=cpu, requires_grad=True)

In [10]:
out = bn(l1(X))
out

Tensor(
[[-0.68578649  2.37775519  0.93317201]
 [ 0.21786862 -0.36380098 -0.25001526]
 [ 1.59955183 -0.13049325 -1.53424854]
 [-1.2868117  -0.52979083  1.15898792]
 [ 0.84299322 -1.41984739 -0.96882459]
 [-1.74799781  0.40095275  1.70727616]
 [ 0.12510938 -0.68025043 -0.19947378]
 [-0.53772274  0.80371928  0.6058936 ]
 [ 0.97331107  0.28344938 -0.89053763]
 [ 0.49948462 -0.74169374 -0.5622299 ]], shape=(10, 3), device=cpu, requires_grad=True)

In [11]:
out = relu(bn(l1(X)))
out

Tensor(
[[0.         2.37775519 0.93317201]
 [0.21786862 0.         0.        ]
 [1.59955183 0.         0.        ]
 [0.         0.         1.15898792]
 [0.84299322 0.         0.        ]
 [0.         0.40095275 1.70727616]
 [0.12510938 0.         0.        ]
 [0.         0.80371928 0.6058936 ]
 [0.97331107 0.28344938 0.        ]
 [0.49948462 0.         0.        ]], shape=(10, 3), device=cpu, requires_grad=True)

In [12]:
out._prev

{Tensor(
 [[-0.68578649  2.37775519  0.93317201]
  [ 0.21786862 -0.36380098 -0.25001526]
  [ 1.59955183 -0.13049325 -1.53424854]
  [-1.2868117  -0.52979083  1.15898792]
  [ 0.84299322 -1.41984739 -0.96882459]
  [-1.74799781  0.40095275  1.70727616]
  [ 0.12510938 -0.68025043 -0.19947378]
  [-0.53772274  0.80371928  0.6058936 ]
  [ 0.97331107  0.28344938 -0.89053763]
  [ 0.49948462 -0.74169374 -0.5622299 ]], shape=(10, 3), device=cpu, requires_grad=True)}

In [13]:
bn = BatchNorm1D(3)
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=cpu, requires_grad=True)
<class 'numpy.ndarray'>


In [14]:
bn.to('gpu')

In [15]:
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=gpu, requires_grad=True)
<class 'cupy.ndarray'>


In [16]:
bn.to('cpu')

In [17]:
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=cpu, requires_grad=True)
<class 'numpy.ndarray'>
