In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from allison import tensor
from allison.nn import Relu,Linear,BatchNorm1D
import allison

In [3]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [4]:
examples = 10
features = 2
classes = 3

In [5]:
# create random data
X = tensor(np.random.randn(examples, features))
X

Tensor(
[[-1.27554491  0.37519911]
 [-0.75036447  0.68361172]
 [ 2.22228825 -0.99880079]
 [-0.53638418 -0.03910041]
 [ 0.46299498 -0.68692171]
 [-0.18582435 -0.09178151]
 [-0.03902431  0.03103795]
 [ 0.28932327 -0.26164971]
 [-0.19814855 -0.56326088]
 [-0.67874647  1.72708295]], shape=(10, 2), device=cpu, requires_grad=False)

In [6]:
relu = Relu()
l1 = Linear(2, 3)
bn = BatchNorm1D(3)

In [7]:
l1(X)

Tensor(
[[-1.45027944e+00 -1.93524121e-01 -3.70121427e-02]
 [-6.56122269e-01  5.51571219e-02  2.17141662e-01]
 [ 2.37981355e+00  2.11160610e-01 -1.13643884e-01]
 [-6.93664192e-01 -1.53258897e-01 -1.17178815e-01]
 [ 2.91997318e-01 -1.30826385e-01 -2.70816920e-01]
 [-2.73613696e-01 -8.16585147e-02 -8.09753146e-02]
 [-3.60447623e-02  1.22024180e-03  8.96270838e-03]
 [ 2.53809384e-01 -2.05607677e-02 -8.27259891e-02]
 [-4.89857118e-01 -2.56988072e-01 -3.26550249e-01]
 [-1.21566956e-01  4.54683527e-01  7.68663203e-01]], shape=(10, 3), device=cpu, requires_grad=True)

In [8]:
relu(X)

Tensor(
[[0.         0.37519911]
 [0.         0.68361172]
 [2.22228825 0.        ]
 [0.         0.        ]
 [0.46299498 0.        ]
 [0.         0.        ]
 [0.         0.03103795]
 [0.28932327 0.        ]
 [0.         0.        ]
 [0.         1.72708295]], shape=(10, 2), device=cpu, requires_grad=False)

In [9]:
relu(l1(X))

Tensor(
[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.51571219e-02 2.17141662e-01]
 [2.37981355e+00 2.11160610e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.91997318e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.22024180e-03 8.96270838e-03]
 [2.53809384e-01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.54683527e-01 7.68663203e-01]], shape=(10, 3), device=cpu, requires_grad=True)

In [10]:
out = bn(l1(X))
out

Tensor(
[[-1.43723679 -0.90541798 -0.11460678]
 [-0.60454566  0.33128852  0.75232746]
 [ 2.57869933  1.10710307 -0.37600236]
 [-0.64390918 -0.70517664 -0.38806023]
 [ 0.38957843 -0.59361844 -0.91212924]
 [-0.20347707 -0.34910372 -0.26456786]
 [ 0.04561915  0.06305723  0.04221626]
 [ 0.34953755 -0.04526101 -0.27053952]
 [-0.43021302 -1.22102795 -1.10223905]
 [-0.04405274  2.31815691  2.63360133]], shape=(10, 3), device=cpu, requires_grad=True)

In [11]:
out = relu(bn(l1(X)))
out

Tensor(
[[0.         0.         0.        ]
 [0.         0.33128852 0.75232746]
 [2.57869933 1.10710307 0.        ]
 [0.         0.         0.        ]
 [0.38957843 0.         0.        ]
 [0.         0.         0.        ]
 [0.04561915 0.06305723 0.04221626]
 [0.34953755 0.         0.        ]
 [0.         0.         0.        ]
 [0.         2.31815691 2.63360133]], shape=(10, 3), device=cpu, requires_grad=True)

In [12]:
out._prev

{Tensor(
 [[-1.43723679 -0.90541798 -0.11460678]
  [-0.60454566  0.33128852  0.75232746]
  [ 2.57869933  1.10710307 -0.37600236]
  [-0.64390918 -0.70517664 -0.38806023]
  [ 0.38957843 -0.59361844 -0.91212924]
  [-0.20347707 -0.34910372 -0.26456786]
  [ 0.04561915  0.06305723  0.04221626]
  [ 0.34953755 -0.04526101 -0.27053952]
  [-0.43021302 -1.22102795 -1.10223905]
  [-0.04405274  2.31815691  2.63360133]], shape=(10, 3), device=cpu, requires_grad=True)}

In [13]:
bn = BatchNorm1D(3)
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=cpu, requires_grad=True)
<class 'numpy.ndarray'>


In [14]:
bn.to('gpu')

In [15]:
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=gpu, requires_grad=True)
<class 'cupy.ndarray'>


In [16]:
bn.to('cpu')

In [17]:
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=cpu, requires_grad=True)
<class 'numpy.ndarray'>
