In [1]:
import numpy as np
from allison.nn import Relu,Linear,Tensor,BatchNorm1D
import allison

In [2]:
device = 'gpu' if allison._cupy_available else 'cpu'
device

if device == 'gpu':
    import cupy as cp

In [3]:
examples = 10
features = 2
classes = 3

In [4]:
# create random data
X = Tensor(np.random.randn(examples, features))
X

Tensor(
[[-0.63246886 -0.54662805]
 [-0.65714098  0.60177598]
 [-0.28595202 -0.40293277]
 [ 0.11305754  1.69714174]
 [ 0.71669903 -1.1763047 ]
 [-0.92089957 -0.31849492]
 [ 2.06169709  0.25334191]
 [-1.04126158  1.41587593]
 [-1.11019192 -0.7866726 ]
 [ 0.30623375  0.01536325]], shape=(10, 2), device=cpu, requires_grad=False)

In [5]:
relu = Relu()
l1 = Linear(2, 3)
bn = BatchNorm1D(3)

In [6]:
l1(X)

Tensor(
[[-0.66562841  0.82421188  0.35924566]
 [ 0.67452878 -1.40096268 -1.85649654]
 [-0.48289231  0.6732868   0.45939415]
 [ 1.98695513 -3.23389144 -3.11307766]
 [-1.34295642  2.53140253  3.0159663 ]
 [-0.41160663  0.2787712  -0.38698527]
 [ 0.38461624  0.26301471  1.74266592]
 [ 1.60878158 -3.1120938  -3.8230049 ]
 [-0.96653798  1.11321911  0.30112353]
 [ 0.03112349  0.08203711  0.30129197]], shape=(10, 3), device=cpu, requires_grad=True)

In [7]:
relu(X)

Tensor(
[[0.         0.        ]
 [0.         0.60177598]
 [0.         0.        ]
 [0.11305754 1.69714174]
 [0.71669903 0.        ]
 [0.         0.        ]
 [2.06169709 0.25334191]
 [0.         1.41587593]
 [0.         0.        ]
 [0.30623375 0.01536325]], shape=(10, 2), device=cpu, requires_grad=False)

In [8]:
relu(l1(X))

Tensor(
[[0.         0.82421188 0.35924566]
 [0.67452878 0.         0.        ]
 [0.         0.6732868  0.45939415]
 [1.98695513 0.         0.        ]
 [0.         2.53140253 3.0159663 ]
 [0.         0.2787712  0.        ]
 [0.38461624 0.26301471 1.74266592]
 [1.60878158 0.         0.        ]
 [0.         1.11321911 0.30112353]
 [0.03112349 0.08203711 0.30129197]], shape=(10, 3), device=cpu, requires_grad=True)

In [9]:
out = bn(l1(X))
out

Tensor(
[[-0.72386934  0.58396823  0.33103647]
 [ 0.57432664 -0.68710246 -0.7816067 ]
 [-0.54685483  0.49775637  0.38132641]
 [ 1.84566004 -1.73411336 -1.41260357]
 [-1.37998975  1.55915464  1.6651186 ]
 [-0.47780115  0.27240001 -0.04368616]
 [ 0.29349145  0.26339955  1.02572609]
 [ 1.47932736 -1.66453975 -1.76909617]
 [-1.01535723  0.74905578  0.30185023]
 [-0.0489332   0.160021    0.30193481]], shape=(10, 3), device=cpu, requires_grad=True)

In [10]:
out = relu(bn(l1(X)))
out

Tensor(
[[0.         0.58396823 0.33103647]
 [0.57432664 0.         0.        ]
 [0.         0.49775637 0.38132641]
 [1.84566004 0.         0.        ]
 [0.         1.55915464 1.6651186 ]
 [0.         0.27240001 0.        ]
 [0.29349145 0.26339955 1.02572609]
 [1.47932736 0.         0.        ]
 [0.         0.74905578 0.30185023]
 [0.         0.160021   0.30193481]], shape=(10, 3), device=cpu, requires_grad=True)

In [11]:
out._prev

{Tensor(
 [[-0.72386934  0.58396823  0.33103647]
  [ 0.57432664 -0.68710246 -0.7816067 ]
  [-0.54685483  0.49775637  0.38132641]
  [ 1.84566004 -1.73411336 -1.41260357]
  [-1.37998975  1.55915464  1.6651186 ]
  [-0.47780115  0.27240001 -0.04368616]
  [ 0.29349145  0.26339955  1.02572609]
  [ 1.47932736 -1.66453975 -1.76909617]
  [-1.01535723  0.74905578  0.30185023]
  [-0.0489332   0.160021    0.30193481]], shape=(10, 3), device=cpu, requires_grad=True)}

In [12]:
bn = BatchNorm1D(3)
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=cpu, requires_grad=True)
<class 'numpy.ndarray'>


In [13]:
bn.to('gpu')

In [14]:
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=gpu, requires_grad=True)
<class 'cupy.ndarray'>


In [15]:
bn.to('cpu')

In [16]:
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=cpu, requires_grad=True)
<class 'numpy.ndarray'>
