[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/Allison/blob/develop/examples/nn/2-layers.ipynb)

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from allison import tensor
from allison.nn import Relu,Linear,BatchNorm1D
import allison

In [3]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [4]:
examples = 10
features = 2
classes = 3

In [5]:
# create random data
X = tensor(np.random.randn(examples, features))
X

Tensor(
[[-0.77274184  1.36287315]
 [ 1.03224782 -0.13219102]
 [-0.13171882 -1.27690064]
 [-0.06225031  1.13193594]
 [ 0.13501055  0.04810326]
 [ 1.4655658   0.27341984]
 [ 0.26067773  0.46784002]
 [-0.26799828  2.04036824]
 [-1.45939264 -0.89063082]
 [-0.36353511  1.82265748]], shape=(10, 2), device=cpu, requires_grad=False)

In [6]:
relu = Relu()
l1 = Linear(2, 3)
bn = BatchNorm1D(3)

In [7]:
l1(X)

Tensor(
[[ 1.06566407  1.04475722 -1.93097876]
 [ 0.28928711 -0.18281936  0.37483164]
 [-1.34942527 -0.90601473  1.64153171]
 [ 1.12280093  0.81839372 -1.49024066]
 [ 0.10417688  0.02306173 -0.03636267]
 [ 0.87850629  0.07165659 -0.06991354]
 [ 0.58153864  0.31387146 -0.55982283]
 [ 1.96000253  1.48845407 -2.71674913]
 [-1.50212657 -0.51553857  0.87705717]
 [ 1.69995189  1.3401995  -2.45118539]], shape=(10, 3), device=cpu, requires_grad=True)

In [8]:
relu(X)

Tensor(
[[0.         1.36287315]
 [1.03224782 0.        ]
 [0.         0.        ]
 [0.         1.13193594]
 [0.13501055 0.04810326]
 [1.4655658  0.27341984]
 [0.26067773 0.46784002]
 [0.         2.04036824]
 [0.         0.        ]
 [0.         1.82265748]], shape=(10, 2), device=cpu, requires_grad=False)

In [9]:
relu(l1(X))

Tensor(
[[1.06566407 1.04475722 0.        ]
 [0.28928711 0.         0.37483164]
 [0.         0.         1.64153171]
 [1.12280093 0.81839372 0.        ]
 [0.10417688 0.02306173 0.        ]
 [0.87850629 0.07165659 0.        ]
 [0.58153864 0.31387146 0.        ]
 [1.96000253 1.48845407 0.        ]
 [0.         0.         0.87705717]
 [1.69995189 1.3401995  0.        ]], shape=(10, 3), device=cpu, requires_grad=True)

In [10]:
out = bn(l1(X))
out

Tensor(
[[ 0.52878072  0.91475318 -0.93406592]
 [-0.17827145 -0.70061245  0.72934648]
 [-1.67065877 -1.65226382  1.64314433]
 [ 0.58081568  0.61688189 -0.61611731]
 [-0.34685269 -0.42969391  0.43271076]
 [ 0.35833476 -0.36574804  0.40850715]
 [ 0.08788415 -0.04701796  0.05508643]
 [ 1.34326129  1.49861301 -1.50092092]
 [-1.80972497 -1.13843701  1.09165214]
 [ 1.10643127  1.30352511 -1.30934315]], shape=(10, 3), device=cpu, requires_grad=True)

In [11]:
out = relu(bn(l1(X)))
out

Tensor(
[[0.52878072 0.91475318 0.        ]
 [0.         0.         0.72934648]
 [0.         0.         1.64314433]
 [0.58081568 0.61688189 0.        ]
 [0.         0.         0.43271076]
 [0.35833476 0.         0.40850715]
 [0.08788415 0.         0.05508643]
 [1.34326129 1.49861301 0.        ]
 [0.         0.         1.09165214]
 [1.10643127 1.30352511 0.        ]], shape=(10, 3), device=cpu, requires_grad=True)

In [12]:
out._prev

{Tensor(
 [[ 0.52878072  0.91475318 -0.93406592]
  [-0.17827145 -0.70061245  0.72934648]
  [-1.67065877 -1.65226382  1.64314433]
  [ 0.58081568  0.61688189 -0.61611731]
  [-0.34685269 -0.42969391  0.43271076]
  [ 0.35833476 -0.36574804  0.40850715]
  [ 0.08788415 -0.04701796  0.05508643]
  [ 1.34326129  1.49861301 -1.50092092]
  [-1.80972497 -1.13843701  1.09165214]
  [ 1.10643127  1.30352511 -1.30934315]], shape=(10, 3), device=cpu, requires_grad=True)}

In [13]:
bn = BatchNorm1D(3)
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=cpu, requires_grad=True)
<class 'numpy.ndarray'>


In [14]:
bn.to('gpu')

In [15]:
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=gpu, requires_grad=True)
<class 'cupy.ndarray'>


In [16]:
bn.to('cpu')

In [17]:
print(bn.gamma)
print(type(bn.running_mean))

Tensor(
[[1. 1. 1.]], shape=(1, 3), device=cpu, requires_grad=True)
<class 'numpy.ndarray'>
