In [1]:
from allison.nn import Tensor,softmax
import numpy as np

In [2]:
a = Tensor(np.array([[1, 2], [3, 4]]))
b = Tensor(np.array([[5, 6], [7, 8]]))
c = Tensor(np.array([[9, 10], [11, 12]]))
d = Tensor(np.array([[13, 14], [15, 16]]))

a + b + c + d

Tensor(
[[28 32]
 [36 40]], shape=(2, 2))

In [3]:
an=a.to_numpy()

In [4]:
type(an)

numpy.ndarray

In [5]:
arr = np.array([[1, 10], [3, 4], [5, 6]])

softmax(arr)

array([[1.23394576e-04, 9.99876605e-01],
       [2.68941421e-01, 7.31058579e-01],
       [2.68941421e-01, 7.31058579e-01]])

In [6]:
a = Tensor(np.array([[1, 2], [3, 4]]))
softmax(a)

Tensor(
[[0.26894142 0.73105858]
 [0.26894142 0.73105858]], shape=(2, 2))