In [1]:

from allison.nn import Tensor,no_grad,Linear
import numpy as np

In [2]:
a = Tensor([1,2,3], requires_grad=True).to('gpu')
b = Tensor([3,4,5], requires_grad=True).to('gpu')
c = a + b
c._prev

{Tensor(
 [1 2 3], shape=(3,), device=gpu, requires_grad=True),
 Tensor(
 [3 4 5], shape=(3,), device=gpu, requires_grad=True)}

In [3]:
with no_grad():
    a = Tensor([1,2,3], requires_grad=True)
    b = Tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

set()

In [7]:
l1 = Linear(2,3)

print(l1.W)
print(l1.b)

Tensor(
[[ 1.01346885  0.18625388 -0.13168498]
 [ 1.44622815 -0.26159669 -0.13427181]], shape=(2, 3), device=cpu, requires_grad=True)
Tensor(
[[0. 0. 0.]], shape=(1, 3), device=cpu, requires_grad=True)


In [9]:
l1.to('gpu')

print(l1.W)
print(l1.b)

Tensor(
[[ 1.01346885  0.18625388 -0.13168498]
 [ 1.44622815 -0.26159669 -0.13427181]], shape=(2, 3), device=gpu, requires_grad=True)
Tensor(
[[0. 0. 0.]], shape=(1, 3), device=gpu, requires_grad=True)
