In [1]:

import allison
from allison.nn import Tensor,no_grad
import numpy as np
import pandas as pd

# Create a Tensor

In [2]:
# from list
tensor = Tensor([1,2,3])
tensor

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [3]:
#from numpy
tensor = Tensor(np.random.rand(5,5))
tensor

Tensor(
[[0.83286157 0.08518032 0.60303991 0.05490197 0.75457467]
 [0.13649788 0.87184639 0.88845842 0.18559029 0.81955133]
 [0.75278304 0.12559375 0.19681215 0.14102939 0.84594789]
 [0.75050379 0.89986717 0.7403375  0.64214234 0.98345637]
 [0.73347108 0.50714312 0.8191356  0.39686823 0.65235498]], shape=(5, 5), device=cpu, requires_grad=False)

In [4]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

tensor = Tensor(data)
tensor

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

# Basic Operations

In [5]:
a = Tensor([1,2,3])
b = Tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [6]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [7]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [8]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [9]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [10]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [11]:
a = Tensor(np.random.rand(5,5))
a

Tensor(
[[0.70158554 0.83430803 0.41611393 0.26554943 0.17377369]
 [0.98325031 0.10713728 0.56926144 0.23204158 0.27255704]
 [0.13870724 0.31390543 0.46185682 0.55548112 0.86494522]
 [0.16960559 0.00178722 0.3530457  0.35128316 0.15387252]
 [0.07439178 0.41511563 0.7699496  0.77478001 0.30637501]], shape=(5, 5), device=cpu, requires_grad=False)

In [12]:
a[3,:]

Tensor(
[0.16960559 0.00178722 0.3530457  0.35128316 0.15387252], shape=(5,), device=cpu, requires_grad=False)

In [13]:
a[3,3]

Tensor(
0.35128316092369205, shape=(), device=cpu, requires_grad=False)

In [14]:
a[:,3]

Tensor(
[0.26554943 0.23204158 0.55548112 0.35128316 0.77478001], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [15]:
a = Tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [16]:
b = Tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [17]:
c = a + b
print(c)
print(c._prev)
print(f'grad(c) {c.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
{Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)}
grad(c) [0 0 0]


In [18]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [19]:
with no_grad():
    a = Tensor([1,2,3], requires_grad=True)
    b = Tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

set()

# Using GPU

In [20]:
device = 'gpu' if allison.is_cuda_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [21]:
a = Tensor(np.random.rand(5,5), device=device)
b = Tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.43520619 1.39216217 1.46502163 1.47010858 0.65642344]
 [1.24952766 0.77137549 0.22612421 1.41863179 1.13006246]
 [0.74866326 0.91443586 1.31793129 0.78788276 0.76198301]
 [0.59219062 1.18413881 1.00700073 1.43067357 0.712273  ]
 [0.92621181 1.16159897 0.67629173 0.89011939 1.24374629]], shape=(5, 5), device=gpu, requires_grad=False)
set()
gpu


In [22]:
a = Tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = Tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.42750157 1.41330702 0.83270508 0.60836427 1.04173894]
 [1.59165204 0.14208176 1.39918374 1.43036861 1.02994999]
 [0.96576329 1.20210097 1.28181329 1.51586843 0.93356176]
 [1.02318856 1.85721187 1.31531417 1.00731117 1.00137066]
 [1.25364113 0.90500361 1.16267262 0.82507572 0.75772887]], shape=(5, 5), device=gpu, requires_grad=True)
{Tensor(
[[0.46018701 0.62462606 0.23960408 0.06698251 0.74229445]
 [0.66529332 0.09861944 0.78759539 0.85070745 0.06250992]
 [0.95945733 0.72809916 0.79925457 0.64121553 0.04832757]
 [0.57233479 0.97582449 0.40712151 0.12548004 0.91565221]
 [0.28859475 0.36174324 0.25185325 0.60353882 0.54146949]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.96731457 0.78868097 0.593101   0.54138177 0.2994445 ]
 [0.92635873 0.04346232 0.61158836 0.57966116 0.96744007]
 [0.00630596 0.47400181 0.48255872 0.8746529  0.8852342 ]
 [0.45085377 0.88138738 0.90819266 0.88183113 0.08571845]
 [0.96504638 0.54326038 0.91081936 0.2215369  0.21625938]], shape=

In [23]:
# to cpu
c = c.to('cpu')
print(c)
print(c.device)

Tensor(
[[1.42750157 1.41330702 0.83270508 0.60836427 1.04173894]
 [1.59165204 0.14208176 1.39918374 1.43036861 1.02994999]
 [0.96576329 1.20210097 1.28181329 1.51586843 0.93356176]
 [1.02318856 1.85721187 1.31531417 1.00731117 1.00137066]
 [1.25364113 0.90500361 1.16267262 0.82507572 0.75772887]], shape=(5, 5), device=cpu, requires_grad=True)
cpu


In [24]:
# to gpu
c = c.to('gpu')
print(c)
print(c.device)

Tensor(
[[1.42750157 1.41330702 0.83270508 0.60836427 1.04173894]
 [1.59165204 0.14208176 1.39918374 1.43036861 1.02994999]
 [0.96576329 1.20210097 1.28181329 1.51586843 0.93356176]
 [1.02318856 1.85721187 1.31531417 1.00731117 1.00137066]
 [1.25364113 0.90500361 1.16267262 0.82507572 0.75772887]], shape=(5, 5), device=gpu, requires_grad=True)
gpu
