[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/Allison/blob/develop/examples/basics/1-tensor.ipynb)


In [1]:
!pip install "allison @ git+https://github.com/Mitchell-Mirano/Allison.git@develop"

zsh:1: command not found: pip


In [2]:
import allison
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = allison.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.49550151 0.71458338 0.43559125 0.40365887 0.8074443 ]
 [0.23920378 0.37317661 0.04578105 0.25237922 0.72671668]
 [0.14572167 0.83917342 0.20754431 0.03884087 0.89028104]
 [0.22882819 0.14828756 0.44114484 0.75568771 0.99455454]
 [0.46668792 0.77466798 0.70256079 0.24572016 0.4469046 ]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = allison.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

In [8]:
# using allison

In [9]:
t = allison.rand(3,4)
t

Tensor(
[[0.98931868 0.18548008 0.6268165  0.57811818]
 [0.34199686 0.60899939 0.60448113 0.99134214]
 [0.98168681 0.14720254 0.15049632 0.35311501]], shape=(3, 4), device=cpu, requires_grad=False)

In [10]:
t = allison.randn(3,4)
t

Tensor(
[[-0.01139312 -0.90888261 -0.3419702   0.96031525]
 [ 0.64958512 -1.21608581 -0.02797998 -0.92198274]
 [ 0.8191681   0.70396617  0.02016003  0.72437453]], shape=(3, 4), device=cpu, requires_grad=False)

In [11]:
t = allison.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [12]:
t = allison.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [31]:
t = allison.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [33]:
t = allison.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [34]:
t = allison.randint(0,10,(3,4))
t

Tensor(
[[2 5 1 7]
 [4 9 6 0]
 [1 4 1 1]], shape=(3, 4), device=cpu, requires_grad=False)

In [35]:
t = allison.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [36]:
t = allison.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [37]:
t = allison.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [38]:
t = allison.randperm(5)
t

Tensor(
[0 2 1 4 3], shape=(5,), device=cpu, requires_grad=False)

# Basic Operations

In [13]:
a = allison.tensor([1,2,3])
b = allison.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [14]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [15]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [16]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [17]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [18]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [19]:
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.4143249  0.59942928 0.90260462 0.41501166 0.80254604]
 [0.43695223 0.09035643 0.19098527 0.58795297 0.28361978]
 [0.6747343  0.94477789 0.74207592 0.60208371 0.15056246]
 [0.92376301 0.84453417 0.79742077 0.69930448 0.21893803]
 [0.72398198 0.91844485 0.52493099 0.39162753 0.58818738]], shape=(5, 5), device=cpu, requires_grad=False)

In [20]:
a[3,:]

Tensor(
[0.92376301 0.84453417 0.79742077 0.69930448 0.21893803], shape=(5,), device=cpu, requires_grad=False)

In [21]:
a[3,3]

Tensor(
0.6993044827987984, shape=(), device=cpu, requires_grad=False)

In [22]:
a[:,3]

Tensor(
[0.41501166 0.58795297 0.60208371 0.69930448 0.39162753], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [23]:
a = allison.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [24]:
b =allison.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [25]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
[Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)]
grad(a) [0 0 0]
grad(b) [0 0 0]


In [26]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [27]:
with allison.no_grad():
    a = allison.tensor([1,2,3], requires_grad=True)
    b = allison.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

[]

# Using GPU

In [28]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [29]:
a = allison.tensor(np.random.rand(5,5), device=device)
b = allison.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.98297095 1.29597857 1.66991859 1.09438372 0.9092465 ]
 [0.98518649 0.85043064 1.15071707 1.44497863 0.90353201]
 [0.73419236 1.0383043  0.84672432 1.36160405 1.08117636]
 [0.86869039 1.39333589 0.8010484  1.00537614 0.62835537]
 [1.04104424 0.67199254 1.03253523 0.98056859 0.2992963 ]], shape=(5, 5), device=gpu, requires_grad=False)
[]
gpu


In [30]:
a = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.01722135 0.52818131 1.16222397 1.36052551 1.41263451]
 [0.78376389 0.14626579 0.40133639 1.30940878 1.09226648]
 [1.2832258  0.54781366 1.20437518 1.10304831 0.57603041]
 [0.66726765 0.56622488 0.55461923 1.02894718 0.79355833]
 [0.86822065 0.96906032 0.80301975 1.01572721 0.3237241 ]], shape=(5, 5), device=gpu, requires_grad=True)
[Tensor(
[[0.95680562 0.22275824 0.56275066 0.4552701  0.82215081]
 [0.67714411 0.14147777 0.17507855 0.68771513 0.38989146]
 [0.73500094 0.12389181 0.50811196 0.71720035 0.33907954]
 [0.59005698 0.02688882 0.11094116 0.0441385  0.33977848]
 [0.00787961 0.31571637 0.56909256 0.47849714 0.02452909]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.06041573 0.30542308 0.59947331 0.90525541 0.5904837 ]
 [0.10661978 0.00478802 0.22625784 0.62169366 0.70237502]
 [0.54822486 0.42392186 0.69626322 0.38584796 0.23695087]
 [0.07721067 0.53933606 0.44367807 0.98480868 0.45377985]
 [0.86034104 0.65334395 0.23392719 0.53723007 0.29919501]], shape=