[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/Allison/blob/develop/examples/basics/1-tensor.ipynb)


In [1]:
!pip install "allison @ git+https://github.com/Mitchell-Mirano/Allison.git@develop"

zsh:1: command not found: pip


In [2]:
import allison
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = allison.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.43957296 0.74489631 0.11072041 0.82069057 0.2714362 ]
 [0.22467222 0.40187403 0.75074499 0.20711355 0.19145292]
 [0.1606481  0.02644028 0.56233867 0.65386187 0.68457177]
 [0.26664105 0.875684   0.92083677 0.51574999 0.81267693]
 [0.10029852 0.05843115 0.33443589 0.15096872 0.6214908 ]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = allison.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

# Basic Operations

In [8]:
a = allison.tensor([1,2,3])
b = allison.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [9]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [10]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [11]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [12]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [13]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [14]:
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.81535184 0.34667926 0.47490747 0.42743304 0.57875454]
 [0.68754178 0.73478662 0.5597532  0.31446369 0.61785375]
 [0.1522479  0.46896631 0.25956517 0.32164936 0.28122117]
 [0.57774109 0.58644248 0.48638807 0.45113306 0.55118047]
 [0.00725546 0.24710056 0.13499331 0.4287467  0.02318545]], shape=(5, 5), device=cpu, requires_grad=False)

In [15]:
a[3,:]

Tensor(
[0.57774109 0.58644248 0.48638807 0.45113306 0.55118047], shape=(5,), device=cpu, requires_grad=False)

In [16]:
a[3,3]

Tensor(
0.45113305846673935, shape=(), device=cpu, requires_grad=False)

In [17]:
a[:,3]

Tensor(
[0.42743304 0.31446369 0.32164936 0.45113306 0.4287467 ], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [18]:
a = allison.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [19]:
b =allison.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [20]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
[Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)]
grad(a) [0 0 0]
grad(b) [0 0 0]


In [21]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [22]:
with allison.no_grad():
    a = allison.tensor([1,2,3], requires_grad=True)
    b = allison.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

[]

# Using GPU

In [23]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

✅ GPU basic operation passed
✅ GPU available: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [24]:
a = allison.tensor(np.random.rand(5,5), device=device)
b = allison.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.6535614  1.28750712 1.08969345 0.84369623 0.84268072]
 [0.73610566 0.62894072 0.61836468 1.0983454  1.02365345]
 [1.22664708 1.04220701 0.60652743 0.26050246 0.85337556]
 [1.76741714 1.18416196 0.73043906 1.62644669 1.07761102]
 [0.76788591 1.70300872 0.92500493 0.72387216 0.73375062]], shape=(5, 5), device=gpu, requires_grad=False)
[]
gpu


In [25]:
a = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.47867623 0.98494773 0.77465222 1.04206503 0.56098818]
 [1.6769288  0.72001066 1.0217526  0.64525718 0.41484945]
 [1.13967533 1.04093314 1.0019358  0.52143507 1.01781863]
 [0.75231594 0.74050573 0.8902844  1.27774388 0.96533476]
 [1.30725254 0.7219786  1.19390817 0.91588809 0.42247481]], shape=(5, 5), device=gpu, requires_grad=True)
[Tensor(
[[0.56681944 0.94401511 0.62041442 0.43925339 0.37803627]
 [0.87524985 0.09737273 0.74755901 0.44981209 0.38667588]
 [0.91513716 0.86485676 0.9549953  0.29680923 0.65412947]
 [0.46768695 0.56520227 0.15896988 0.76536055 0.25950466]
 [0.7971137  0.16402057 0.9192062  0.67217619 0.1997009 ]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.9118568  0.04093262 0.15423779 0.60281163 0.18295191]
 [0.80167895 0.62263793 0.27419358 0.1954451  0.02817357]
 [0.22453818 0.17607638 0.04694049 0.22462584 0.36368916]
 [0.28462899 0.17530346 0.73131452 0.51238334 0.70583009]
 [0.51013884 0.55795803 0.27470196 0.2437119  0.22277391]], shape=