[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/Allison/blob/develop/examples/nn/1-tensor.ipynb)


In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import allison
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = allison.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.89740364 0.73908519 0.30358512 0.51533669 0.74637378]
 [0.63034774 0.80263747 0.03320732 0.6762267  0.93308311]
 [0.62416224 0.21813    0.14346444 0.05149243 0.69871151]
 [0.0778844  0.17406864 0.0329327  0.8059136  0.65704445]
 [0.03199347 0.55039647 0.36058765 0.28304254 0.76602574]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = allison.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

# Basic Operations

In [8]:
a = allison.tensor([1,2,3])
b = allison.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [9]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [10]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [11]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [12]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [13]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [14]:
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.07804223 0.93162929 0.97201644 0.38383966 0.10135398]
 [0.79613948 0.44027403 0.89150447 0.79803997 0.42135048]
 [0.17273527 0.41466884 0.30134535 0.8487878  0.09425338]
 [0.04012496 0.50477871 0.28259341 0.1115843  0.0626001 ]
 [0.01417838 0.8134125  0.82966138 0.22869257 0.57411407]], shape=(5, 5), device=cpu, requires_grad=False)

In [15]:
a[3,:]

Tensor(
[0.04012496 0.50477871 0.28259341 0.1115843  0.0626001 ], shape=(5,), device=cpu, requires_grad=False)

In [16]:
a[3,3]

Tensor(
0.1115842950667727, shape=(), device=cpu, requires_grad=False)

In [17]:
a[:,3]

Tensor(
[0.38383966 0.79803997 0.8487878  0.1115843  0.22869257], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [18]:
a = allison.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [19]:
b =allison.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [20]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
{Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True), Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)}
grad(a) [0 0 0]
grad(b) [0 0 0]


In [21]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [22]:
with allison.no_grad():
    a = allison.tensor([1,2,3], requires_grad=True)
    b = allison.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

set()

# Using GPU

In [23]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
CuPy version: 13.6.0


'gpu'

In [24]:
a = allison.tensor(np.random.rand(5,5), device=device)
b = allison.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.96211422 1.03473968 0.87016542 1.30404585 0.52459083]
 [1.6168224  1.04802313 1.47696698 0.3311566  1.63461505]
 [0.73383862 0.91996789 1.1755237  0.38763971 0.88002705]
 [0.99623269 0.29406068 1.33304354 1.02939932 1.4873554 ]
 [0.53803421 1.03476532 0.51162572 0.27864018 0.47228964]], shape=(5, 5), device=gpu, requires_grad=False)
set()
gpu


In [25]:
a = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.64050152 1.35228281 0.31758935 1.42051729 1.11071777]
 [0.85194269 0.63496905 1.1695972  0.51578058 0.85258023]
 [0.1252341  0.40723964 1.61564388 1.56655724 1.67940852]
 [0.84160476 0.46112169 0.76738871 0.4413747  0.88657615]
 [1.60003825 0.41109945 0.1708961  1.4182609  1.46034995]], shape=(5, 5), device=gpu, requires_grad=True)
{Tensor(
[[0.35814204 0.51072385 0.12184392 0.79660551 0.12099481]
 [0.35984996 0.09659787 0.86733333 0.03506062 0.48303636]
 [0.11440138 0.01646439 0.63402787 0.8221863  0.76413849]
 [0.48859178 0.29237165 0.49630521 0.19326474 0.78834544]
 [0.89563902 0.22841948 0.04827741 0.45069873 0.49532096]], shape=(5, 5), device=gpu, requires_grad=True), Tensor(
[[0.28235948 0.84155896 0.19574543 0.62391179 0.98972296]
 [0.49209273 0.53837118 0.30226387 0.48071996 0.36954387]
 [0.01083272 0.39077525 0.98161601 0.74437094 0.91527002]
 [0.35301298 0.16875004 0.2710835  0.24810996 0.09823071]
 [0.70439923 0.18267997 0.12261869 0.96756217 0.96502899]], shape=