[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/Allison/blob/develop/examples/basics/1-tensor.ipynb)


In [1]:
!pip install "allison @ git+https://github.com/Mitchell-Mirano/Allison.git@develop"

zsh:1: command not found: pip


In [2]:
import allison
import numpy as np
import pandas as pd

# Create a Tensor

In [3]:
# from list
a = allison.tensor([1,2,3])
a

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)

In [4]:
a.shape

(3,)

In [5]:
len(a)

3

In [6]:
#from numpy
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.93564425 0.07767454 0.15806842 0.74773013 0.52936161]
 [0.68983707 0.42233775 0.47241826 0.06536248 0.91836849]
 [0.8965154  0.29513523 0.60957187 0.07065311 0.79259716]
 [0.47587685 0.87324818 0.11826629 0.36953333 0.32668575]
 [0.04393649 0.54523369 0.08728872 0.58989044 0.04693529]], shape=(5, 5), device=cpu, requires_grad=False)

In [7]:
# from pandas

data = pd.DataFrame({
    'a': [0.464307, 0.182403, 0.664873, 0.906638, 0.725385],
    'b': [0.278199, 0.187902, 0.887387, 0.473387, 0.904510],
    'c': [0.793136, 0.957675, 0.035765, 0.639977, 0.622032],
    'd': [0.618634, 0.784397, 0.841349, 0.352944, 0.783273],
    'e': [0.729128, 0.467162, 0.687347, 0.432614, 0.980809]
})

t = allison.tensor(data)
t

Tensor(
[[0.464307 0.278199 0.793136 0.618634 0.729128]
 [0.182403 0.187902 0.957675 0.784397 0.467162]
 [0.664873 0.887387 0.035765 0.841349 0.687347]
 [0.906638 0.473387 0.639977 0.352944 0.432614]
 [0.725385 0.90451  0.622032 0.783273 0.980809]], shape=(5, 5), device=cpu, requires_grad=False)

In [8]:
# using allison

In [9]:
t = allison.as_tensor([1,2,3])
t

AttributeError: module 'allison' has no attribute 'as_tensor'

In [ ]:
t = allison.randn(3,4)
t

Tensor(
[[ 1.00162838  1.40477213 -0.4121589  -0.43484851]
 [-1.20273354  0.79066301 -0.34844084  0.94505413]
 [-0.95222546 -0.98745034  1.27768044 -0.9736496 ]], shape=(3, 4), device=cpu, requires_grad=False)

In [ ]:
t = allison.zeros((3,4))
t

Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), device=cpu, requires_grad=False)

In [ ]:
t = allison.ones((3,4))
t

Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), device=cpu, requires_grad=False)

In [ ]:
t = allison.eye(3)
t

Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), device=cpu, requires_grad=False)

In [ ]:
t = allison.diag([1,2,3])
t

Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), device=cpu, requires_grad=False)

In [ ]:
t = allison.randint(0,10,(3,4))
t

Tensor(
[[4 8 4 1]
 [2 2 2 0]
 [5 3 3 1]], shape=(3, 4), device=cpu, requires_grad=False)

In [ ]:
t = allison.arange(0,10)
t

Tensor(
[0 1 2 3 4 5 6 7 8 9], shape=(10,), device=cpu, requires_grad=False)

In [ ]:
t = allison.linspace(0,10,5)
t

Tensor(
[ 0.   2.5  5.   7.5 10. ], shape=(5,), device=cpu, requires_grad=False)

In [ ]:
t = allison.logspace(0,10,5)
t

Tensor(
[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10], shape=(5,), device=cpu, requires_grad=False)

In [ ]:
t = allison.randperm(5)
t

Tensor(
[4 3 0 2 1], shape=(5,), device=cpu, requires_grad=False)

# Basic Operations

In [ ]:
a = allison.tensor([1,2,3])
b = allison.tensor([3,4,5])

print(a)
print(b)

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=False)
Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=False)


In [ ]:
c = a + b
c

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=False)

In [ ]:
c = a - b
c

Tensor(
[-2 -2 -2], shape=(3,), device=cpu, requires_grad=False)

In [ ]:
c = a * b
c

Tensor(
[ 3  8 15], shape=(3,), device=cpu, requires_grad=False)

In [ ]:
c = a@b
c

Tensor(
26, shape=(), device=cpu, requires_grad=False)

In [ ]:
c = a**2
c

Tensor(
[1 4 9], shape=(3,), device=cpu, requires_grad=False)

# Spliting

In [ ]:
a = allison.tensor(np.random.rand(5,5))
a

Tensor(
[[0.62440978 0.67821807 0.01393296 0.12442269 0.67606529]
 [0.75931367 0.62713019 0.15366794 0.73190277 0.99420111]
 [0.14036067 0.27116646 0.42761078 0.07322539 0.2818224 ]
 [0.24407951 0.81527013 0.28132355 0.40349775 0.11209673]
 [0.03490303 0.43061261 0.62932456 0.94973952 0.38953775]], shape=(5, 5), device=cpu, requires_grad=False)

In [ ]:
a[3,:]

Tensor(
[0.24407951 0.81527013 0.28132355 0.40349775 0.11209673], shape=(5,), device=cpu, requires_grad=False)

In [ ]:
a[3,3]

Tensor(
0.40349775488412454, shape=(), device=cpu, requires_grad=False)

In [ ]:
a[:,3]

Tensor(
[0.12442269 0.73190277 0.07322539 0.40349775 0.94973952], shape=(5,), device=cpu, requires_grad=False)

# Auto Grad

In [ ]:
a = allison.tensor([1,2,3], requires_grad=True)
print(a)
print(f'grad(a) {a.grad}')

Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True)
grad(a) [0 0 0]


In [ ]:
b =allison.tensor([3,4,5], requires_grad=True)
print(b)
print(f'grad(b) {b.grad}')

Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)
grad(b) [0 0 0]


In [ ]:
c = a + b
print(c)
print(c._prev)
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

Tensor(
[4 6 8], shape=(3,), device=cpu, requires_grad=True)
[Tensor(
[1 2 3], shape=(3,), device=cpu, requires_grad=True), Tensor(
[3 4 5], shape=(3,), device=cpu, requires_grad=True)]
grad(a) [0 0 0]
grad(b) [0 0 0]


In [ ]:
c.backward()
print(f'grad(a) {a.grad}')
print(f'grad(b) {b.grad}')

grad(a) [1 1 1]
grad(b) [1 1 1]


In [ ]:
with allison.no_grad():
    a = allison.tensor([1,2,3], requires_grad=True)
    b = allison.tensor([3,4,5], requires_grad=True)
    c = a + b

c._prev

[]

# Using GPU

In [ ]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

❌ CuPy is not installed.


'cpu'

In [ ]:
a = allison.tensor(np.random.rand(5,5), device=device)
b = allison.tensor(np.random.rand(5,5), device=device)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[1.23218966 0.27767731 0.53358842 1.51184264 0.99364066]
 [0.9387508  0.4985025  1.18142425 0.7744069  1.93757497]
 [1.23831691 1.39149862 0.44149546 1.15589336 1.32000168]
 [1.55172236 0.83963135 1.06266734 1.51726906 0.82349263]
 [0.81410312 1.17185763 1.85513199 1.28254324 1.88380501]], shape=(5, 5), device=cpu, requires_grad=False)
[]
cpu


In [ ]:
a = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
b = allison.tensor(np.random.rand(5,5), device=device,requires_grad=True)
c = a + b
print(c)
print(c._prev)
print(c.device)

Tensor(
[[0.65497467 0.95829618 0.38069026 0.71213526 1.26143717]
 [0.87162343 0.08989108 0.80992943 0.54599584 1.36158544]
 [1.13253421 0.55504808 1.20290518 0.86528915 0.22456642]
 [1.43524855 0.94833907 0.65357053 0.73029568 0.8643551 ]
 [0.706289   1.37470168 0.8715388  1.06256988 0.9052634 ]], shape=(5, 5), device=cpu, requires_grad=True)
[Tensor(
[[0.64146686 0.69788396 0.1083924  0.06240867 0.63928599]
 [0.23587356 0.01178312 0.17043369 0.10866429 0.46729882]
 [0.4590796  0.25979962 0.59061508 0.63106995 0.10177988]
 [0.83281808 0.69970452 0.44864687 0.67444008 0.19787116]
 [0.25786225 0.71787399 0.0225089  0.32340479 0.48665071]], shape=(5, 5), device=cpu, requires_grad=True), Tensor(
[[0.0135078  0.26041222 0.27229786 0.64972659 0.62215118]
 [0.63574986 0.07810796 0.63949574 0.43733155 0.89428661]
 [0.6734546  0.29524846 0.61229009 0.2342192  0.12278655]
 [0.60243047 0.24863455 0.20492366 0.05585559 0.66648394]
 [0.44842675 0.65682769 0.8490299  0.73916509 0.41861268]], shape=