[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Mitchell-Mirano/Allison/blob/develop/examples/basics/2-layers.ipynb)

In [ ]:
!pip install allison

zsh:1: command not found: pip


In [136]:
import numpy as np
from allison import tensor
from allison.nn import Relu,Linear,BatchNorm1D
import allison

In [137]:
features = 5
classes = 2
examples = 10

In [138]:
# create random data
X = tensor(np.random.randn(examples, features))
X

Tensor(
[[ 1.09955408 -0.61479012  0.5254415  -0.77422902  0.08078718]
 [ 1.60580775 -0.51344912  0.88591578 -0.43847554 -1.03297307]
 [-0.35500228 -1.69551001 -0.87658408 -0.35523567 -1.55357449]
 [-0.11836415 -1.74628712 -0.10863481 -2.26727951 -1.84774679]
 [ 0.02943422  1.83413251  0.57113285  0.22603153  0.74336546]
 [ 0.80567609  0.19394742  0.68820108 -0.29941399  1.03266462]
 [ 0.73428039 -0.43162977  2.45183933 -0.05825815 -1.2947397 ]
 [ 0.36821491  0.79308876  0.55337089 -0.32441566  0.82558739]
 [-0.89667355 -0.17673987 -0.27434219  1.55945159 -0.11691754]
 [ 1.74347773 -1.17425804 -1.16762295  1.01972838  0.85815937]], shape=(10, 5), device=cpu, requires_grad=False)

# Linear

In [139]:
linear = Linear(features,classes)
linear.W,linear.b

(Tensor(
 [[-0.12625551 -0.52090245]
  [ 1.26463255 -0.03568576]
  [ 0.7683735  -0.53196216]
  [ 0.24526001  0.66649112]
  [ 0.10870139 -0.32024855]], shape=(5, 2), device=cpu, requires_grad=True),
 Tensor(
 [[0. 0.]], shape=(1, 2), device=cpu, requires_grad=True))

In [140]:
linear(X)

Tensor(
[[-0.69367878 -1.3722249 ]
 [-0.39117845 -1.25085196]
 [-3.02892095  0.97250525]
 [-3.03386516 -0.73762004]
 [ 2.89087215 -0.47201955]
 [ 0.71116445 -1.32296286]
 [ 1.09033998 -1.29556118]
 [ 1.39184853 -0.99509173]
 [ 0.04866373  1.69612952]
 [-2.25891744  0.15966931]], shape=(10, 2), device=cpu, requires_grad=True)

# Batch Norm

In [141]:
bn = BatchNorm1D(classes)
bn.gamma,bn.beta

(Tensor(
 [[1. 1.]], shape=(1, 2), device=cpu, requires_grad=True),
 Tensor(
 [[0. 0.]], shape=(1, 2), device=cpu, requires_grad=True))

In [142]:
bn(linear(X))

Tensor(
[[-0.1957029  -0.89493792]
 [-0.03409133 -0.77562926]
 [-1.44331203  1.40991382]
 [-1.44595349 -0.27112622]
 [ 1.71935263 -0.01004297]
 [ 0.5548382  -0.84651372]
 [ 0.7574137  -0.81957808]
 [ 0.91849542 -0.52421891]
 [ 0.20089549  2.12123093]
 [-1.03193568  0.61090233]], shape=(10, 2), device=cpu, requires_grad=True)

# ReLU

In [143]:
relu = Relu()
relu(X)

Tensor(
[[1.09955408 0.         0.5254415  0.         0.08078718]
 [1.60580775 0.         0.88591578 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.02943422 1.83413251 0.57113285 0.22603153 0.74336546]
 [0.80567609 0.19394742 0.68820108 0.         1.03266462]
 [0.73428039 0.         2.45183933 0.         0.        ]
 [0.36821491 0.79308876 0.55337089 0.         0.82558739]
 [0.         0.         0.         1.55945159 0.        ]
 [1.74347773 0.         0.         1.01972838 0.85815937]], shape=(10, 5), device=cpu, requires_grad=False)

# Linear + ReLU

In [144]:
relu(linear(X))

Tensor(
[[0.         0.        ]
 [0.         0.        ]
 [0.         0.97250525]
 [0.         0.        ]
 [2.89087215 0.        ]
 [0.71116445 0.        ]
 [1.09033998 0.        ]
 [1.39184853 0.        ]
 [0.04866373 1.69612952]
 [0.         0.15966931]], shape=(10, 2), device=cpu, requires_grad=True)

# Linear + BatchNorm + ReLU

In [145]:
relu(bn(linear(X)))

Tensor(
[[0.         0.        ]
 [0.         0.        ]
 [0.         1.40991382]
 [0.         0.        ]
 [1.71935263 0.        ]
 [0.5548382  0.        ]
 [0.7574137  0.        ]
 [0.91849542 0.        ]
 [0.20089549 2.12123093]
 [0.         0.61090233]], shape=(10, 2), device=cpu, requires_grad=True)

Without bias

In [146]:
linear = Linear(features,classes,bias=False)
relu(bn(linear(X)))

Tensor(
[[0.22865682 0.57132872]
 [0.         0.53122008]
 [0.         0.        ]
 [0.         1.00872521]
 [1.50568675 0.56171964]
 [1.13079566 0.49400445]
 [0.0910277  0.60704171]
 [1.22941469 0.65281757]
 [0.         0.        ]
 [0.         0.        ]], shape=(10, 2), device=cpu, requires_grad=True)

# Using GPU

In [147]:
device = 'gpu' if allison.cuda.is_available() else 'cpu'
device

Current GPU: NVIDIA GeForce RTX 4070 Laptop GPU
CUDA runtime version: 13000
Backend: CuPy, version: 13.6.0


'gpu'

# Linear

In [148]:
features = 5
classes = 2
examples = 10

X = tensor(np.random.randn(examples, features), device=device)
linear = Linear(features,classes).to(device)
linear(X)

Tensor(
[[-2.50123456 -2.10368518]
 [ 1.53204359  2.20858764]
 [ 0.45376497  1.1683612 ]
 [-2.00394528 -1.03469659]
 [ 0.1207449  -0.57056546]
 [-0.28004949  1.41484886]
 [ 0.23224996 -1.55518476]
 [ 1.37882402  1.66993815]
 [-3.02881528 -0.48927983]
 [-0.10414598  0.1705214 ]], shape=(10, 2), device=gpu, requires_grad=True)

# Batch Norm

In [149]:
bn = BatchNorm1D(classes).to(device)
bn(linear(X))

Tensor(
[[-1.39386853 -1.57082657]
 [ 1.30741835  1.52003231]
 [ 0.58524155  0.774441  ]
 [-1.06080917 -0.80461975]
 [ 0.36220146 -0.47194974]
 [ 0.09376953  0.95111317]
 [ 0.43688194 -1.17768415]
 [ 1.20479958  1.13395062]
 [-1.74721556 -0.41368756]
 [ 0.21158085  0.05923068]], shape=(10, 2), device=gpu, requires_grad=True)

# ReLU

In [150]:
relu = Relu()
relu(X)

Tensor(
[[0.12844535 0.         0.         0.         0.        ]
 [0.         1.04515484 0.         1.65149395 1.7226863 ]
 [1.34044505 0.17048716 1.07252816 0.         0.        ]
 [0.15042588 0.10593068 0.15122031 2.52292222 0.        ]
 [0.         0.         0.67558986 0.         0.        ]
 [1.95420365 0.         0.2475612  0.         0.15894051]
 [0.         0.         0.23472575 0.         0.        ]
 [0.68837868 0.         0.02137914 0.73449355 1.20377089]
 [0.         2.19853637 0.         1.11053711 0.16618472]
 [0.63653433 0.         0.         0.         0.01729508]], shape=(10, 5), device=gpu, requires_grad=False)

# Linear + ReLU + Batch Norm

In [151]:
relu(bn(linear(X)))

Tensor(
[[0.         0.        ]
 [1.30741835 1.52003231]
 [0.58524155 0.774441  ]
 [0.         0.        ]
 [0.36220146 0.        ]
 [0.09376953 0.95111317]
 [0.43688194 0.        ]
 [1.20479958 1.13395062]
 [0.         0.        ]
 [0.21158085 0.05923068]], shape=(10, 2), device=gpu, requires_grad=True)